name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
    paths: [ 'api/functions/**' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: api/functions/package-lock.json

    - name: Install dependencies
      run: |
        cd api/functions
        npm ci

    - name: Build
      run: |
        cd api/functions
        npm run build

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'func-xob7nugiarm7e'
        package: 'api/functions'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
