name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
    paths: [ 'api/functions/**' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: api/functions/package-lock.json

      - name: Install dependencies
        working-directory: api/functions
        run: npm ci

      - name: Build
        working-directory: api/functions
        run: npm run build

      - name: Verify dependencies
        working-directory: api/functions
        run: |
          echo "Checking critical dependencies..."
          ls -la node_modules/@azure/functions || echo "ERROR: @azure/functions not found!"
          ls -la node_modules/openai || echo "ERROR: openai not found!"

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: func-xob7nugiarm7e
          package: api/functions
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: false
          enable-oryx-build: false
